version: "3.7"

services:
  django:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./config/env/.env.dev
    depends_on:
      - database

  database:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - ./config/env/.env.dev.db

volumes:
  postgres_data_dev:
