version: "3.7"

services:
  django:
    build: ./app
    command: gunicorn acm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./config/env/.env.prod
    depends_on:
      - postgres

  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/env/.env.prod.db

  nginx:
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    image: nginx:1.15-alpine
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - ./config/nginx-dev:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume:
